version: '3.8'

services:
  backend:
    build: ./backend
    container_name: dashboard-backend
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=3001
    restart: unless-stopped
    networks:
      - dashboard-network

  frontend:
    build: ./frontend
    container_name: dashboard-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge
